### ISSUE TITLE
Ian, this looks really great!

### ISSUE THREAD

**Issue by zigmoo** [ianmiell/introduction-to-bash#1]
Hello Ian,

I really like your approach to teaching and using bash!

Even though I've used bash/ksh/zsh and sh for a long time, I've already learned a few things that are new to me just by a light read of your material here!

Thank you,

Jason Ziegler

PS: There's a typo on slide 23 on the word that should be "Outputting".

**Comment by ianmiell** [comment]
Thanks Jason!

This is the materials for my O'Reilly course: 

https://www.oreilly.com/live-training/courses/introduction-to-the-bash-shell/0636920267348/

You might not be aware that I wrote a book on bash here:

https://leanpub.com/learnbashthehardway
